insert into docks (dock_address, capacity, number_of_bikes) values ('73856 Schurz Terrace', 30, 30);
insert into docks (dock_address, capacity, number_of_bikes) values ('9397 Fairview Place', 40, 21);
insert into docks (dock_address, capacity, number_of_bikes) values ('78306 4th Street', 40, 30);
insert into docks (dock_address, capacity, number_of_bikes) values ('6392 Pawling Alley', 30, 27);
insert into docks (dock_address, capacity, number_of_bikes) values ('491 Shopko Plaza', 30, 28);
insert into docks (dock_address, capacity, number_of_bikes) values ('7616 Oriole Alley', 30, 23);
insert into docks (dock_address, capacity, number_of_bikes) values ('6690 Spenser Drive', 40, 20);
insert into docks (dock_address, capacity, number_of_bikes) values ('3130 Grayhawk Circle', 30, 26);
insert into docks (dock_address, capacity, number_of_bikes) values ('4968 Forest Run Point', 40, 27);
insert into docks (dock_address, capacity, number_of_bikes) values ('18893 Rieder Alley', 40, 29);
insert into docks (dock_address, capacity, number_of_bikes) values ('2112 Bay Junction', 30, 21);
insert into docks (dock_address, capacity, number_of_bikes) values ('77127 Towne Park', 30, 20);
insert into docks (dock_address, capacity, number_of_bikes) values ('21989 Toban Crossing', 40, 21);
insert into docks (dock_address, capacity, number_of_bikes) values ('77 Northwestern Junction', 30, 23);
insert into docks (dock_address, capacity, number_of_bikes) values ('748 Dennis Park', 30, 26);
insert into docks (dock_address, capacity, number_of_bikes) values ('69 Farwell Trail', 40, 28);
insert into docks (dock_address, capacity, number_of_bikes) values ('63 Swallow Plaza', 30, 23);
insert into docks (dock_address, capacity, number_of_bikes) values ('7 Ohio Drive', 30, 21);
insert into docks (dock_address, capacity, number_of_bikes) values ('83466 Buena Vista Crossing', 30, 27);
insert into docks (dock_address, capacity, number_of_bikes) values ('17395 Hallows Plaza', 30, 28);
insert into docks (dock_address, capacity, number_of_bikes) values ('4 Heath Lane', 30, 30);
insert into docks (dock_address, capacity, number_of_bikes) values ('84526 Logan Circle', 30, 27);
insert into docks (dock_address, capacity, number_of_bikes) values ('20 Steensland Street', 40, 29);
insert into docks (dock_address, capacity, number_of_bikes) values ('17 Iowa Parkway', 30, 29);
insert into docks (dock_address, capacity, number_of_bikes) values ('5 Brickson Park Point', 30, 23);
insert into docks (dock_address, capacity, number_of_bikes) values ('3 Mandrake Crossing', 40, 25);
insert into docks (dock_address, capacity, number_of_bikes) values ('649 Blue Bill Park Road', 40, 22);
insert into docks (dock_address, capacity, number_of_bikes) values ('43952 Elka Way', 30, 30);
insert into docks (dock_address, capacity, number_of_bikes) values ('8559 John Wall Plaza', 40, 21);
insert into docks (dock_address, capacity, number_of_bikes) values ('83 Becker Court', 30, 22);
insert into docks (dock_address, capacity, number_of_bikes) values ('115 Cody Plaza', 30, 28);
insert into docks (dock_address, capacity, number_of_bikes) values ('47903 Glacier Hill Crossing', 40, 26);
insert into docks (dock_address, capacity, number_of_bikes) values ('1 Division Road', 40, 28);
insert into docks (dock_address, capacity, number_of_bikes) values ('16 North Crossing', 30, 26);
insert into docks (dock_address, capacity, number_of_bikes) values ('88071 Farwell Place', 40, 22);
insert into docks (dock_address, capacity, number_of_bikes) values ('243 Sauthoff Avenue', 30, 21);
insert into docks (dock_address, capacity, number_of_bikes) values ('3415 Fuller Avenue', 30, 24);
insert into docks (dock_address, capacity, number_of_bikes) values ('062 Messerschmidt Street', 30, 26);
insert into docks (dock_address, capacity, number_of_bikes) values ('5 Elgar Avenue', 40, 26);
insert into docks (dock_address, capacity, number_of_bikes) values ('9 Annamark Street', 40, 23);
insert into docks (dock_address, capacity, number_of_bikes) values ('18342 Memorial Hill', 40, 30);
insert into docks (dock_address, capacity, number_of_bikes) values ('70598 8th Plaza', 40, 26);
insert into docks (dock_address, capacity, number_of_bikes) values ('53876 Blaine Park', 40, 24);
insert into docks (dock_address, capacity, number_of_bikes) values ('12681 Walton Trail', 40, 24);
insert into docks (dock_address, capacity, number_of_bikes) values ('5655 Fuller Court', 40, 29);
insert into docks (dock_address, capacity, number_of_bikes) values ('3768 Doe Crossing Junction', 40, 28);
insert into docks (dock_address, capacity, number_of_bikes) values ('629 Thompson Lane', 30, 21);
insert into docks (dock_address, capacity, number_of_bikes) values ('16626 Doe Crossing Drive', 30, 23);
insert into docks (dock_address, capacity, number_of_bikes) values ('843 Maple Park', 30, 23);
insert into docks (dock_address, capacity, number_of_bikes) values ('2 Ohio Crossing', 40, 23);
insert into docks (dock_address, capacity, number_of_bikes) values ('898 Debra Park', 30, 24);
insert into docks (dock_address, capacity, number_of_bikes) values ('63 Old Gate Junction', 30, 28);
insert into docks (dock_address, capacity, number_of_bikes) values ('9 Village Hill', 30, 23);
insert into docks (dock_address, capacity, number_of_bikes) values ('43 Vahlen Pass', 40, 28);
insert into docks (dock_address, capacity, number_of_bikes) values ('63627 Westridge Trail', 30, 20);
insert into docks (dock_address, capacity, number_of_bikes) values ('9837 New Castle Center', 40, 30);
insert into docks (dock_address, capacity, number_of_bikes) values ('399 Merchant Avenue', 40, 26);
insert into docks (dock_address, capacity, number_of_bikes) values ('81833 Esch Point', 30, 28);
insert into docks (dock_address, capacity, number_of_bikes) values ('1356 Homewood Plaza', 40, 29);
insert into docks (dock_address, capacity, number_of_bikes) values ('0 Lunder Trail', 40, 22);
insert into docks (dock_address, capacity, number_of_bikes) values ('87 North Way', 30, 28);
insert into docks (dock_address, capacity, number_of_bikes) values ('6774 Independence Junction', 30, 25);
insert into docks (dock_address, capacity, number_of_bikes) values ('9359 Bunting Street', 30, 28);
insert into docks (dock_address, capacity, number_of_bikes) values ('5906 Pennsylvania Junction', 40, 22);
insert into docks (dock_address, capacity, number_of_bikes) values ('02 Hagan Avenue', 40, 20);
insert into docks (dock_address, capacity, number_of_bikes) values ('3174 Eagan Lane', 40, 25);
insert into docks (dock_address, capacity, number_of_bikes) values ('6 Heffernan Trail', 40, 26);
insert into docks (dock_address, capacity, number_of_bikes) values ('60 School Hill', 30, 20);
insert into docks (dock_address, capacity, number_of_bikes) values ('85773 Mariners Cove Drive', 40, 29);
insert into docks (dock_address, capacity, number_of_bikes) values ('1379 Blue Bill Park Hill', 40, 26);
insert into docks (dock_address, capacity, number_of_bikes) values ('6 Burrows Hill', 30, 26);
insert into docks (dock_address, capacity, number_of_bikes) values ('423 Carioca Terrace', 40, 27);
insert into docks (dock_address, capacity, number_of_bikes) values ('851 Ohio Court', 30, 26);
insert into docks (dock_address, capacity, number_of_bikes) values ('61 Daystar Plaza', 40, 25);
insert into docks (dock_address, capacity, number_of_bikes) values ('329 Sage Junction', 30, 26);
insert into docks (dock_address, capacity, number_of_bikes) values ('5 Fuller Hill', 40, 26);
insert into docks (dock_address, capacity, number_of_bikes) values ('530 Northland Lane', 30, 26);
insert into docks (dock_address, capacity, number_of_bikes) values ('840 East Pass', 40, 22);
insert into docks (dock_address, capacity, number_of_bikes) values ('20 Pine View Junction', 40, 25);
insert into docks (dock_address, capacity, number_of_bikes) values ('440 Lake View Road', 40, 25);
insert into docks (dock_address, capacity, number_of_bikes) values ('65 Hudson Junction', 40, 28);
insert into docks (dock_address, capacity, number_of_bikes) values ('31 Melby Hill', 30, 23);
insert into docks (dock_address, capacity, number_of_bikes) values ('01873 Sachtjen Center', 30, 27);
insert into docks (dock_address, capacity, number_of_bikes) values ('664 Bay Junction', 40, 30);
insert into docks (dock_address, capacity, number_of_bikes) values ('9 Golf Place', 40, 23);
insert into docks (dock_address, capacity, number_of_bikes) values ('46417 Schlimgen Way', 30, 25);
insert into docks (dock_address, capacity, number_of_bikes) values ('2086 Starling Hill', 40, 20);
insert into docks (dock_address, capacity, number_of_bikes) values ('9476 Waywood Junction', 30, 29);
insert into docks (dock_address, capacity, number_of_bikes) values ('5 Cambridge Avenue', 40, 25);
insert into docks (dock_address, capacity, number_of_bikes) values ('83548 West Street', 30, 26);
insert into docks (dock_address, capacity, number_of_bikes) values ('4 Del Mar Parkway', 30, 21);
insert into docks (dock_address, capacity, number_of_bikes) values ('94 Petterle Drive', 30, 25);
insert into docks (dock_address, capacity, number_of_bikes) values ('40 Everett Junction', 30, 22);
insert into docks (dock_address, capacity, number_of_bikes) values ('9720 Barnett Center', 40, 30);
insert into docks (dock_address, capacity, number_of_bikes) values ('9 Lukken Plaza', 30, 29);
insert into docks (dock_address, capacity, number_of_bikes) values ('50 Johnson Alley', 30, 23);
insert into docks (dock_address, capacity, number_of_bikes) values ('23 Springs Terrace', 40, 21);
insert into docks (dock_address, capacity, number_of_bikes) values ('5 Northview Way', 30, 24);
insert into docks (dock_address, capacity, number_of_bikes) values ('54508 Ramsey Place', 40, 20);apacity, number_of_bike) values ('82629 Dayton Crossing', 40, 27);
insert into docks (dock_address, capacity, number_of_bike) values ('14679 Vera Junction', 40, 22);
insert into docks (dock_address, capacity, number_of_bike) values ('0 Hintze Way', 40, 28);
insert into docks (dock_address, capacity, number_of_bike) values ('11145 Green Court', 40, 21);
insert into docks (dock_address, capacity, number_of_bike) values ('759 Holy Cross Pass', 30, 27);
insert into docks (dock_address, capacity, number_of_bike) values ('4574 Pepper Wood Center', 30, 29);
insert into docks (dock_address, capacity, number_of_bike) values ('0 Meadow Valley Court', 30, 30);
insert into docks (dock_address, capacity, number_of_bike) values ('6167 Daystar Center', 40, 20);
insert into docks (dock_address, capacity, number_of_bike) values ('6 Caliangt Avenue', 40, 22);
insert into docks (dock_address, capacity, number_of_bike) values ('5 Burrows Crossing', 30, 26);
insert into docks (dock_address, capacity, number_of_bike) values ('84488 Oriole Street', 40, 25);
insert into docks (dock_address, capacity, number_of_bike) values ('08 Northview Crossing', 30, 22);
insert into docks (dock_address, capacity, number_of_bike) values ('54853 Ryan Way', 30, 28);
insert into docks (dock_address, capacity, number_of_bike) values ('5342 Bay Parkway', 40, 20);
insert into docks (dock_address, capacity, number_of_bike) values ('683 Jackson Point', 30, 23);
insert into docks (dock_address, capacity, number_of_bike) values ('49 Village Road', 40, 29);
insert into docks (dock_address, capacity, number_of_bike) values ('90584 Longview Trail', 30, 24);
insert into docks (dock_address, capacity, number_of_bike) values ('42 Marcy Plaza', 30, 28);
insert into docks (dock_address, capacity, number_of_bike) values ('851 Gale Alley', 30, 20);
insert into docks (dock_address, capacity, number_of_bike) values ('64247 Lighthouse Bay Plaza', 30, 23);
insert into docks (dock_address, capacity, number_of_bike) values ('3 Melody Parkway', 40, 24);
insert into docks (dock_address, capacity, number_of_bike) values ('9 Bluestem Pass', 30, 23);