insert into docks (dock_address, capacity, number_of_bikes) values ('73856 Schurz Terrace', 30, 30);
insert into docks (dock_address, capacity, number_of_bikes) values ('9397 Fairview Place', 40, 21);
insert into docks (dock_address, capacity, number_of_bikes) values ('78306 4th Street', 40, 30);
insert into docks (dock_address, capacity, number_of_bikes) values ('6392 Pawling Alley', 30, 27);
insert into docks (dock_address, capacity, number_of_bikes) values ('491 Shopko Plaza', 30, 28);
insert into docks (dock_address, capacity, number_of_bikes) values ('7616 Oriole Alley', 30, 23);
insert into docks (dock_address, capacity, number_of_bikes) values ('6690 Spenser Drive', 40, 20);
insert into docks (dock_address, capacity, number_of_bikes) values ('3130 Grayhawk Circle', 30, 26);
insert into docks (dock_address, capacity, number_of_bikes) values ('4968 Forest Run Point', 40, 27);
insert into docks (dock_address, capacity, number_of_bikes) values ('18893 Rieder Alley', 40, 29);
